### ISSUE TITLE
DT1 - Anotar nombre de cliente

### ISSUE THREAD

**Issue by nigmasilmi** [ClaudiaQuezadaRiquelme/SCL010-Burger-Queen#1]

**Comment by nigmasilmi** [comment]
Tareas previas:

- [x] 1. Desarrollo de esqueleto html y reglas css en estático como patrones para darle estilo a los componentes referentes a esta historia de usuario.
- [x] 2. Crear servicio que tome el valor ingresado por el usuario en el input type text del formulario de ingreso de nombre.

**3.** Crear funciones en el servicio de input-order que creen el documento en firebase con el nombre del usuario
**4.** Crear servicio común que tome los productos seleccionados como parte de la orden que se está ingresando y los añada al documento creado a partir de su id.

**Comment by ClaudiaQuezadaRiquelme** [comment]
3. => Se probó crear en el servicio input-order documento en firebase con el nombre del cliente y orden vacía.
4. => No se logró añadir la orden al cliente con su id específico porque no fue posible guardar el id del documento generado, porque los documentos de firebase son creados a partir de promesas y las promesas no retornan otra cosa que no sean promesas.

**Comment by ClaudiaQuezadaRiquelme** [comment]
Plan alternativo para 3. y 4. :
- [x] 3b. Crear funciones en el servicio de input-order que guarden en una variable el nombre del usuario.
- [x] 4b. Utilizar el servicio input-order.service.ts como intermediario para pasar el nombre del usuario desde un componente a otro, y así guardar el documento de firebase con nombre de cliente y su orden.

**Comment by nigmasilmi** [comment]
Es posible retornar valores de id de firebase utilizando el método snapshotChanges de angularfire2. Los detalles y código de ejemplo en el slack.
