### ISSUE TITLE
DT2 - Marcar los pedidos que se han terminado

### ISSUE THREAD

**Issue by nigmasilmi** [ClaudiaQuezadaRiquelme/SCL010-Burger-Queen#12]
- [x] 1. Añadir checkbox a cada pedido en cocina
---- Agregar una nueva columna
---- En cada fila, añadir checkbox con id que utilice el id del producto más un identificador. Ej: check_index
- [x] 2. Añadir botón confirmar junto a checkbox
---- Agregar una nueva columna
---- En cada fila, añadir botón con id que utilice el id del producto más un identificador. Ej: button_index
- [x] 3. Cuando se confirme, cambia el estado 'enCocina' por 'Delivereded'. Esto debería eliminar automáticamente el pedido de la lista de pedidos en cocina.

**Comment by ClaudiaQuezadaRiquelme** [comment]
Confirmar Pedido:
- [x] El botón confirmar sólo se habilita cuando el checkbox está activado. Si no, no funciona
- [x] Función que confirma si checkbox está activado, debe recibir id del ckeckbox + id del botón
Observación: Cuando le agregas un evento a cada botón, no es necesario usar el id del checkbox y del botón para que el evento funcione. De todas formas necesitamos que el botón tome el id de la orden para cambiarle el status
