### ISSUE TITLE
DT2 - Agregar productos al pedido

### ISSUE THREAD

**Issue by nigmasilmi** [ClaudiaQuezadaRiquelme/SCL010-Burger-Queen#2]
- [x] Agregar colección de productos a Firestore
- [x] Llamar data de Firestore y mostrarla en pantalla
- [x] Hacer que los productos sean botones
- [x] cuando presiones un producto, agregarlo a un arreglo vacío
- [x] imprime en consola el arreglo para ver si están agregándose los productos

**Comment by ClaudiaQuezadaRiquelme** [comment]
**Hacer que los productos sean botones**
- [x] Agregar etiqueta button
- [x] Evento en el botón que envíe el producto a un arreglo

**Comment by ClaudiaQuezadaRiquelme** [comment]
GUARDAR PRODUCTOS EN FIREBASE
- [x] Crear function en servicio
- [x] esa función tiene que llamar a add(). Recibe el nombre del cliente, la orden, (VALOR DE LA ORDEN).
- [x] dentro de add, crear objeto antes de pushear (si le pusheas directamente un array, firebase da error)

**Comment by ClaudiaQuezadaRiquelme** [comment]
- [x] Cuando se envíen los productos a Firestore, tienes que borrar el contenido del array => no es necesario, se "borran" solos.
- [x] Elegir menú Breakfast o Traditional

**Comment by ClaudiaQuezadaRiquelme** [comment]
**Elegir menú Breakfast o Traditional**
- [x] Mostrar botones que te den a elegir entre menú breakfast o traditional.
- [x] Cuando presiones botón, ocultar botones y mostrar menú que corresponde a ese menú. 
     Para eso usa *ngIf
